/**
 * Playlist route keys (M18 task 5.3; spec `sharing` — "A playlist shares its own
 * page URL").
 *
 * `/playlist/[id]` is addressed by the local playlist's own id — a
 * `crypto.randomUUID()`, generated by the repository when the playlist is created
 * and never derived from anything the listener typed. There is no text half to
 * this route the way `/artist/[key]` and `/album/[key]` have, and deliberately
 * so: a playlist is a record on **this device**, so there is nothing outside it
 * for a name to resolve against, and no provider has ever heard of it.
 *
 * **The route is percent-encoded anyway.** A uuid needs no encoding, and that is
 * exactly why the encoding has to be here rather than left implicit: an id with a
 * `/` or a `&` in it would build a link that navigates somewhere else, and the
 * only thing standing between a caller and that is this function. `tests/share-links.test.ts`
 * pins both halves.
 *
 * Pure, like its two sibling key modules: no repository, no network, no framework
 * import — and the single owner of the playlist-route format, so no call site can
 * concatenate one.
 */

/** Route prefix for a playlist page. */
const PLAYLIST_ROUTE = "/playlist";

/**
 * The playlist route for `id`.
 *
 * Trimmed before it is encoded, so an id that arrived with stray whitespace builds
 * the same link a clean one does — the same rule `artistKeys` and `albumKeys`
 * apply, for the same reason: a link and the key it was built from must not be
 * able to disagree.
 */
export function playlistHref(id: string): string {
  return `${PLAYLIST_ROUTE}/${encodeURIComponent(id.trim())}`;
}
